import { SITE_URL } from "@/lib/site";

export const EMAIL_TEMPLATES = [
  {
    id: "announcement",
    name: "Announcement",
    description: "General platform news or important customer update.",
    subject: "An update from TrollzStore",
    eyebrow: "TrollzStore Update",
    title: "Here is what is new at TrollzStore",
    accent: "#ff4a1c",
    ctaLabel: "Shop on TrollzStore",
    ctaUrl: `${SITE_URL}/shop`,
  },
  {
    id: "promo",
    name: "Promotion",
    description: "Deals, discounts, flash sales, and seasonal campaigns.",
    subject: "Fresh deals are waiting for you",
    eyebrow: "Special Offer",
    title: "A little something for your next order",
    accent: "#111827",
    ctaLabel: "Explore Deals",
    ctaUrl: `${SITE_URL}/shop?tab=flash`,
  },
  {
    id: "order",
    name: "Order Update",
    description: "Useful order, delivery, payment, or support information.",
    subject: "Important update about your TrollzStore order",
    eyebrow: "Order Support",
    title: "We have an update for you",
    accent: "#0f766e",
    ctaLabel: "Track Order",
    ctaUrl: `${SITE_URL}/track-order`,
  },
  {
    id: "seller-trust",
    name: "Seller Trust",
    description: "Verified seller, marketplace safety, and trust messaging.",
    subject: "Shop confidently with verified sellers",
    eyebrow: "Buyer Protection",
    title: "Every seller is verified. Every order is protected.",
    accent: "#7c3aed",
    ctaLabel: "Browse Verified Products",
    ctaUrl: `${SITE_URL}/shop`,
  },
];
